### ISSUE TITLE
Time-based rotation

### ISSUE THREAD

**Issue by finostrozac** [edward-shen/MMM-page-indicator#1]
Is there any way to customize the other pages? any idea? can't find the answer :( Thanks!

**Comment by edward-shen** [comment]
Hey!

Please check out the companion module [MMM-Pages](https://github.com/edward-shen/MMM-pages) for exactly what you need!

**Comment by finostrozac** [comment]
Thank you!, it works perfect!, is there any way to change pages more dinamically?

**Comment by edward-shen** [comment]
MMM-page-indicator does provide a way to change the pages by clicking the dot of the page you want to go to, but nothing more than that. Usually, you'd get some other module to change it for you.

I did plan on making it have a timer to rotate out, but I can't work on this project right now.

**Comment by edward-shen** [comment]
[MMM-pages](https://github.com/edward-shen/MMM-pages) now implements this feature. Please check and update your config files there to get time-based rotation.
