### ISSUE TITLE
change the page

### ISSUE THREAD

**Issue by ajmax666** [edward-shen/MMM-page-indicator#10]
Hi, how do I change the page after i run the program? And will it work with touchscreen?

Thank you

**Comment by edward-shen** [comment]
This module does not provide an ergonomic way to manipulate the pages. Please consider [MMM-touch](https://github.com/gfischershaw/MMM-Touch) for touch screen input.

**Comment by Macster999** [comment]
I use MMM-page-indicator, which automatically change the pages for you, and also gives you the option to click with a mouse or your finger on buttons to go to different pages.  I have the buttons displayed in the Bottom Bar.

**Comment by edward-shen** [comment]
I'm closing this issue due to old age. Please feel free to reopen this issue if you still have a problem.
