### ISSUE TITLE
Indicator loses order

### ISSUE THREAD

**Issue by fnsign** [edward-shen/MMM-page-indicator#14]
Hi,
I use MMM-pages together with MMM-page-indicator. For changing the pages i use MMM-GroveGesture.
MMM-GroveGestures allows me to swipe pages forth and back. The gestures are detected by a small gesture sensor which is also used by the module author (https://github.com/eouia/MMM-GroveGestures). All 3 modules worked fine together. Around the release of MM v2.14 (I can't say for sure) the indcator gest out of sync with the order of the displayed pages.

E.g.:
When MM is started or wakes up from sleep, the indicator is on the first position and displays page0 (which is correct). When I swipe to the next page (page1), then page1 is displayed, but the indicator overjumps the second position and displays the 3rd (which would be page2). The further I swipe the more confused gets the indicator and shows always the wrong position. When the mirror goes to sleep and wakes up gain, then the indicator is again on the 1st position and the home page (page0) is displayed.
As said before the combo worked flawlessly together, but somehow it changed.

**Comment by Burnallover** [comment]
Hi Edward, just fyi I have the exact same issue on mine.

**Comment by Ax-LED** [comment]
@edward-shen 
Today i upgraded my MagicMirror install to 2.17 and had the same issue.
Deleting/uncomment the lines you suggested works for me.
Regards
AxLED

**Comment by Antislag** [comment]
Hi Edward, 
I got the same problem. Is there a solution, yet?
