### ISSUE TITLE
Support for custom Icons

### ISSUE THREAD

**Issue by stephenjgray** [edward-shen/MMM-page-indicator#2]
Hi,

I have added support for custom icons and styling in a fork of this repo, thought you might want to take a look...

https://github.com/stephenjgray/MMM-page-indicator

**Comment by edward-shen** [comment]
Hey! Thanks for the fork!

What you should do next is to make a pull request. I'll formally check what you've done and if everything's good, I'll merge it!

**Comment by E3V3A** [comment]
@stephenjgray  Please post a PR.

**Comment by stephenjgray** [comment]
Hey,

I think I ran into a permissions issue, either with cutting a branch or
pushing changes to it.

Feel free to either pull my changes from the fork or copy and paste them,
or what ever is easiest...

**Comment by edward-shen** [comment]
Closing in favor of #3.
