### ISSUE TITLE
Indicator getting black if page_changed is used

### ISSUE THREAD

**Issue by McNose** [edward-shen/MMM-page-indicator#4]
Hi again,

guess I found a little something here.
When I use `page_increment / decrement` the indicator moves to the correct page.
Using `page_changed` the white indicator disappears. Both of my circles are getting black.
The page changes correctly anyway.
If I use `increment/ decrement` again the white indicator is back again. But sometimes at a wrong position.

I use MMM-remote-control so my command code is `http://ip:8080/remote?action=NOTIFICATION&notification=PAGE_CHANGED&payload="1"
Because it works I dont think that my code is wrong.

I am fine using` increment / decrement.` Anyway I wanted to let you know.

Thanks again.

**Comment by McNose** [comment]
Oh. I am really sorry for this. Your code works fine.
Thank you very much.

**Comment by edward-shen** [comment]
No, I'm glad to be of use. Please don't hesitate to open up more issues if you have any problems!
