### ISSUE TITLE
 The pages do not change by clicking with the mouse.

### ISSUE THREAD

**Issue by ErasmoMMM** [edward-shen/MMM-page-indicator#8]
Hello! Thank you for your magnificent module that I am combining with MMM-Pages. I have a problem. When I click on the module circles to change the page, it does not take any action. Only sometimes changes the page but rarely.
This is my configuration ...

	modules: [
	{
	module: 'MMM-pages',
        config: {
                modules:
                   [	
		//     Página principal - PRINCIPAL
		        ["updatenotification", "MMM-UVIndex", "MMM-AirQuality", "MMM-Tools", "compliments", "weatherforecast"],
	        //       Página 2 - MI CALENDARIO
		        ["MMM-CalendarExt2"],
		//     Página 3 - EL TIEMPO PERDOMO/GÁLDAR/MADRID
                        ["calendar", "MMM-DarkSkyForecast"],
		//     Página 4 - NOTICIAS
		       ["newsfeed", "MMM-TouchPlayerBasic", "MMM-network-signal"],
		//     Página 5 - PERSONAL
                       ["MMM-GooglePhotos", "MMM-GoogleFit", "MMM-GoogleFit2"],
		//     Página 6 - UD LAS PALMAS
		       ["MMM-BackgroundSlideshow", "MMM-SimpleLogo", "MMM-NewsFeedTicker", "MMM-Widget"],
		   ],
                fixed: ["clock", "currentweather", "MMM-LocalTemperature", "MMM-WeatherDependentClothes", "MMM-TelegramBot", "alert", "MMM-Cursor", "MMM-GroveGestures", "MMM-page-indicator"],
		animationTime: "3000",
		rotationTime: "300000",
		delayTime: "600000"
	}
   },

And in bottom_left (as last module), I have the following:

{
        module: 'MMM-page-indicator',
        position: 'bottom_bar',
        config: {
        }
    }, 

Searching on Google I found a solution that is not working. Include in custom.css the following:

}
.fullscreen.above {
  z-index: -1;
}

But the problem remains and I can't change the page correctly with the mouse.
Could you give me any suggestions about it?
Thanks in advance!!

**Comment by edward-shen** [comment]
The mouse support is very limited, as usually you use another way to change the pages such as a timer or a button. Clicking on the actual dots was only really meant for debugging purposes.

Do you not have any other way to chagne the buttons?

**Comment by ErasmoMMM** [comment]
Okay.  No problem.  I use MMM-Grove-Gesture and it goes very well to change the pages.  It was only to know if he was doing something wrong.  Perfect and thank you very much!

**Comment by edward-shen** [comment]
Yeah, sorry about that! Glad to see you have a workaround.
